<?php
/**
 * Database configuration file
 * Generated by installation wizard
 */

// Database configuration
define('DB_HOST', 'localhost');
define('DB_USER', 'username_here');
define('DB_PASS', 'password_here');
define('DB_NAME', 'database_name_here');

// System version
define('SYSTEM_VERSION', '1.0.0');

// Security keys (generate unique values for production)
define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');

// Table prefix
$table_prefix = '';

// Language
define('LANG', 'fa_IR');

// Debug mode
define('DEBUG', false);

// Database connection
try {
    $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
    $conn->set_charset('utf8mb4');
    if ($conn->connect_error) {
        throw new Exception('Database connection failed: ' . $conn->connect_error);
    }
} catch (Exception $e) {
    if (!defined('WP_INSTALLING')) {
        die('Database error: ' . $e->getMessage());
    }
}

/* That's all, stop editing! Happy managing. */

/** Sets up vars and included files. */
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
